version: '3.8'



     
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    hostname: mysql-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social-media-api
      MYSQL_USER: socialmedia
      MYSQL_PASSWORD: root
    ports:
      - "5001:3306"
